# Generated by Django 3.2.9 on 2021-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0002_alter_billing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
