# Generated by Django 3.2.9 on 2021-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0004_auto_20211105_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(blank=True, default='blank', null=True, upload_to='posts/photos'),
        ),
    ]
