# Generated by Django 3.2.9 on 2021-11-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0005_alter_file_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='billing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='billing.billing'),
            preserve_default=False,
        ),
    ]
