# Generated by Django 3.2.9 on 2021-11-05 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0006_file_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
